apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container-deploy
  namespace: default
  labels:
    app: multi-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multi-app
  template:
    metadata:
      labels:
        app: multi-app
    spec:
      containers:
        - name: nginx
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
              name: nginx-port
        - name: multitool
          image: wbitt/network-multitool
          env:
            - name: HTTP_PORT
              value: "8080"
            - name: HTTPS_PORT
              value: "11443"
          ports:
            - containerPort: 8080
              name: tool-port






