apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-init-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-conditional
  template:
    metadata:
      labels:
        app: nginx-conditional
    spec:
      initContainers:
        - name: wait-for-svc
          image: busybox:1.36
          command: ['sh', '-c', 'until nslookup conditional-svc.default.svc.cluster.local; do echo waiting for service; sleep 2; done']
      containers:
        - name: nginx
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
